### ISSUE TITLE
Alternative constructor that accepts multiple pairs as varargs?

### ISSUE THREAD

**Issue by ali-ramadhan** [charleskawczynski/DispatchedTuples.jl#10]
The first thing I tried (because I didn't read the README carefully enough) was

```julia
dt = DispatchedTuple(Center() => "c", Face() => "f")
```

which didn't work because the input needs to be a tuple of pairs. 

Would it helpful to users to define a constructor like

```julia
julia> DispatchedTuple(multiple_pairs...) = DispatchedTuple(Tuple(multiple_pairs))
```

so that the initial example works:

```julia
julia> dt = DispatchedTuple(Center() => "c", Face() => "f")
DispatchedTuple{Tuple{Tuple{Center, String}, Tuple{Face, String}}, DispatchedTuples.NoDefaults}(((Center(), "c"), (Face(), "f")), DispatchedTuples.NoDefaults())
```

**Comment by charleskawczynski** [comment]
I completely agree. I'm not sure how we can get that while still having a default argument while also avoiding keywords (which is purely my paranoia due to [this issue](https://github.com/JuliaGPU/KernelAbstractions.jl/issues/114)). Maybe we can make a typed parameter constructor that has different interfaces?

**Comment by charleskawczynski** [comment]
Going to experiment a bit

**Comment by ali-ramadhan** [comment]
Ah I guess `default` could become a keyword argument?

I think https://github.com/JuliaGPU/KernelAbstractions.jl/issues/114 might not apply here since the kwarg is just for the constructor and isn't used in the `@kernel`?

Unless you're constructing `DispatchedTuple`s in kernels...

**Comment by charleskawczynski** [comment]
Yeah, I'd like for it to be fully gpu-friendly-- that said, based on how I think this might be used in ClimateMachine, I don't _think_ the constructors will be used in gpu kernels.
