### ISSUE TITLE
Why does indexing a `DispatchedTuple` always return a tuple?

### ISSUE THREAD

**Issue by ali-ramadhan** [charleskawczynski/DispatchedTuples.jl#12]
I noticed that indexing a `DispatchedTuple` always returns a tuple:

```julia
julia> dispatch(dt, Center())
("c",)
```

which I thought might introduce lots of `[1]` boilerplate if I used it since I usually want the contents of the 1-tuple

```julia
julia> dispatch(dt, Center())[1]
"c"
```

but maybe this is because I'm focusing on the case where each object maps to just one value.

Is it always returning a tuple because you want the type of the output to always be `<:Tuple`? I guess returning `[1]` in the case of a 1-tuple might introduce type instability?

**Comment by charleskawczynski** [comment]
> Is it always returning a tuple because you want the type of the output to always be <:Tuple?

I think so, yes. `DispatchedSet`s return the value:

```julia
using DispatchedTuples
struct Foo end;
struct Bar end;
struct Baz end;

tup = (
   Pair(Foo(), 1),
   Pair(Bar(), 3),
)

dtup = DispatchedSet(tup);

dispatch(dtup, Foo()) # returns 1
dispatch(dtup, Bar()) # returns 3
dispatch(dtup, Baz()) # error

dtup = DispatchedSet(tup, 0);

dispatch(dtup, Foo()) # returns 1
dispatch(dtup, Bar()) # returns 3
dispatch(dtup, Baz()) # returns 0
```

**Comment by charleskawczynski** [comment]
> I guess returning [1] in the case of a 1-tuple might introduce type instability?

Yeah, probably

**Comment by ali-ramadhan** [comment]
Ah thanks for the clarification. Indeed `DispatchedSet` is probably what I want in this case.

I guess this suggests that you want to be iterating over the result of indexing a `DispatchedTuple`, e.g.

```julia
for v in dt[Face()]
    # do something with v...
end
```

which will always do the right thing.

**Comment by charleskawczynski** [comment]
> I guess this suggests that you want to be iterating over the result of indexing a DispatchedTuple,

Yes, exactly
