### ISSUE TITLE
Should we not export `dispatch` and externally rely on `getindex(dtup, i) = dispatch(dtup, i)`?

### ISSUE THREAD

**Issue by charleskawczynski** [charleskawczynski/DispatchedTuples.jl#21]

**Comment by ali-ramadhan** [comment]
Not sure if there are any limitations but when using DispatchedTuples.jl I only use `getindex` via e.g. `dtup[Foo()]` and never the `dispatch` function, which might actually have an overly vague/generic name?

**Comment by charleskawczynski** [comment]
True, true. Let's do it.

**Comment by charleskawczynski** [comment]
I just remembered that I was interested in [nesting DispatchedTuples](https://github.com/charleskawczynski/DispatchedTuples.jl/blob/main/test/runtests.jl#L148-L167), which is supported through [this implementation](https://github.com/charleskawczynski/DispatchedTuples.jl/blob/main/src/DispatchedTuples.jl#L176). I'm wondering if this syntax still makes sense, since it then looks like a multidimensional array 🤔

**Comment by charleskawczynski** [comment]
I think it should be fine 🤷🏻‍♂️
